name: Node CI

# Push tests pushes; PR tests merges; create tests tags (and releases)
on: [push, pull_request, create]

jobs:

  # Test the build
  build:
    # Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    # Go
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Versions
      run: node --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test

  # ----- Only git tag testing + package publishing beyond this point ----- #

  # Publish to package registries
  publish:
    # Setup
    needs: build
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    # Go
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm ci

      - name: Publish @LTS to npm
        run: npm publish --tag LTS
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Errors when publishing to GitHub with an alternate tag, so disabling
      # # Set up Node again, this time using GitHub as the publish target
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      #     registry-url: https://npm.pkg.github.com/

      # - name: Publish @LTS to GitHub
      #   run: npm publish --tag LTS
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
